# Generated by Django 5.0.3 on 2024-04-24 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="sign_images/category_images/")),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                ("content_id", models.AutoField(primary_key=True, serialize=False)),
                ("alphabet_title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="sign_images/content_images/")),
                ("slug", models.SlugField(unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hasta_sense.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("video_id", models.AutoField(primary_key=True, serialize=False)),
                ("video_title", models.CharField(max_length=100)),
                ("video_file", models.FileField(upload_to="video_files/")),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hasta_sense.content",
                    ),
                ),
            ],
        ),
    ]
