# Generated by Django 5.0.3 on 2024-04-24 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hasta_sense", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="alphabet_title",
            new_name="content_title",
        ),
    ]
