# Generated by Django 5.0.3 on 2024-04-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hasta_sense", "0003_content_content_sign_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="image",
        ),
        migrations.AddField(
            model_name="content",
            name="content_image",
            field=models.ImageField(
                default="default_image.png",
                upload_to="sign_images/contents/content_sign_thumbnail/",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="word_image",
            field=models.ImageField(
                default="default_image.png", upload_to="sign_images/words/word_image/"
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="content_sign_video",
            field=models.FileField(
                default="default_video.mp4",
                upload_to="sign_images/contents/content_sign_videos/",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                default="default_video.mp4", upload_to="sign_images/words/word_video/"
            ),
        ),
    ]
