# Generated by Django 5.0.3 on 2024-04-24 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hasta_sense", "0004_remove_content_image_content_content_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                ("word_id", models.AutoField(primary_key=True, serialize=False)),
                ("word_title", models.CharField(max_length=100)),
                (
                    "word_image",
                    models.ImageField(
                        default="default_image.png",
                        upload_to="sign_images/words/word_image/",
                    ),
                ),
                (
                    "word_video_file",
                    models.FileField(
                        default="default_video.mp4",
                        upload_to="sign_images/words/word_video/",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hasta_sense.content",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
