# Generated by Django 5.0.3 on 2024-04-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hasta_sense", "0005_word_delete_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="category",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="word",
            name="content",
            field=models.IntegerField(),
        ),
    ]
