# Generated by Django 5.0.3 on 2024-04-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hasta_sense", "0006_alter_content_category_alter_word_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="category",
            field=models.CharField(max_length=100),
        ),
    ]
