# Generated by Django 5.0.3 on 2024-05-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hasta_sense", "0009_alter_content_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("user", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
