# Generated by Django 5.0.3 on 2024-05-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hasta_sense", "0011_alter_review_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.IntegerField(),
        ),
    ]
