# Generated by Django 5.0.3 on 2024-05-03 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hasta_sense", "0013_review_created_at"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Review",
            new_name="Feedback",
        ),
    ]
