# Generated by Django 5.0.3 on 2024-05-03 04:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hasta_sense", "0014_rename_review_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="review_id",
            new_name="feedback_id",
        ),
    ]
